using System;
using System.Collections.Generic;

namespace SICEM_Blazor.Models.Entities.Arquos
{
    public partial class VwOprFactura
    {
        public string IdFactura { get; set; }
        public decimal IdTipomovto { get; set; }
        public DateTime? Fecha { get; set; }
        public decimal? IdPadron { get; set; }
        public decimal? IdCuenta { get; set; }
        public decimal? FSubtotal { get; set; }
        public decimal? FIva { get; set; }
        public decimal? FTotal { get; set; }
        public decimal? ASubtotal { get; set; }
        public decimal? AIva { get; set; }
        public decimal? ATotal { get; set; }
        public decimal? DSubtotal { get; set; }
        public decimal? DIva { get; set; }
        public decimal? DTotal { get; set; }
        public decimal? PSubtotal { get; set; }
        public decimal? PIva { get; set; }
        public decimal? PTotal { get; set; }
        public decimal? XSubtotal { get; set; }
        public decimal? XIva { get; set; }
        public decimal? XTotal { get; set; }
        public decimal? SSubtotal { get; set; }
        public decimal? SIva { get; set; }
        public decimal? STotal { get; set; }
        public decimal? IdSucursal { get; set; }
        public string IdGenero { get; set; }
        public decimal? IdEstatus { get; set; }
        public string ObservaA { get; set; }
        public bool? EsRezago { get; set; }
        public DateTime? PasoARezago { get; set; }
        public string IdCancelo { get; set; }
        public DateTime? FechaCancelo { get; set; }
        public string ObservaC { get; set; }
        public decimal? Mf { get; set; }
        public decimal? Af { get; set; }
        public decimal? PromedioAct { get; set; }
        public decimal? PromedioAnt { get; set; }
        public decimal? MesAdeudoAnt { get; set; }
        public decimal? MesAdeudoAct { get; set; }
        public decimal? IdServicio { get; set; }
        public decimal? IdTarifa { get; set; }
        public decimal? IdTarifafija { get; set; }
        public decimal? IdSituacion { get; set; }
        public decimal? IdAnomaliaAnt { get; set; }
        public decimal? IdAnomaliaAct { get; set; }
        public DateTime? FechaLecturaAnt { get; set; }
        public DateTime? FechaLecturaAct { get; set; }
        public decimal? LecturaAnt { get; set; }
        public decimal? LecturaAct { get; set; }
        public decimal? ConsumoAnt { get; set; }
        public decimal? ConsumoAct { get; set; }
        public DateTime? FechaVencimientoAnt { get; set; }
        public DateTime? FechaVencimientoAct { get; set; }
        public decimal? Longitud { get; set; }
        public decimal? Latitud { get; set; }
        public string Handheld { get; set; }
        public bool? Normal { get; set; }
        public decimal? IdTipocalculo { get; set; }
        public decimal? IdTipocalculado { get; set; }
        public decimal? FolioOperacion { get; set; }
        public decimal? IdLecturista { get; set; }
        public DateTime? FechaCapturo { get; set; }
        public string IdCapturo { get; set; }
        public DateTime? FechaSubio { get; set; }
        public decimal? IdDepartamento { get; set; }
        public decimal? IdLocalidad { get; set; }
        public decimal? Recibo { get; set; }
        public int Sb { get; set; }
        public int Sector { get; set; }
        public decimal ConsumoReal { get; set; }
        public decimal ConsumoAnidado { get; set; }
        public decimal Subsidio { get; set; }
        public bool? EsDraef { get; set; }
        public DateTime? FechaInsert { get; set; }
        public string Tipomovto { get; set; }
        public string Sucursal { get; set; }
        public string Genero { get; set; }
        public string Estatus { get; set; }
        public string Cancelo { get; set; }
        public string Servicio { get; set; }
        public string Tarifa { get; set; }
        public string Tarifafija { get; set; }
        public string Situacion { get; set; }
        public string AnomaliaAnt { get; set; }
        public string AnomaliaAct { get; set; }
        public string Tipocalculo { get; set; }
        public string Tipocalculado { get; set; }
        public string Lecturista { get; set; }
        public string Capturo { get; set; }
        public string Localidad { get; set; }
        public string Fecha1 { get; set; }
        public string Ciclo { get; set; }
        public string PasoARezago1 { get; set; }
        public string FechaCancelo1 { get; set; }
        public string FechaLecturaAnt1 { get; set; }
        public string FechaLecturaAct1 { get; set; }
        public string FechaVencimientoAnt1 { get; set; }
        public string FechaVencimientoAct1 { get; set; }
        public string FechaCapturo1 { get; set; }
        public string FechaSubio1 { get; set; }
        public string FechaInsert1 { get; set; }
    }
}
